[profile.default]
src = "src"
out = "out"
libs = ["lib"]
private_key = "${PRIVATE_KEY}"
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
fuji = "https://api.avax-test.network/ext/bc/C/rpc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
